#!/usr/bin/env bash
#
# Resume Sync Audit — consistency check across all resume outputs.
#
# Architecture assumption:
#   - src/data/resume.ts       = Single Source of Truth (leaf data)
#   - Web/PDF .astro files     = Import from data.ts (verified via import check)
#   - Obsidian resume-common.md= Auto-generated by gen-resume-md.ts (leaf)
#   - LinkedIn about.md ko     = Auto-generated by gen-linkedin-about.ts (leaf)
#
# The audit checks:
#   1. All "leaf" files (data.ts, common, LinkedIn) contain key facts
#   2. Web/PDF import from resume.ts (so they inherit the data)
#   3. No forbidden strings anywhere
#
# Run: bash scripts/resume-audit.sh
# Or:  npm run resume:audit

set -uo pipefail

# ─── Targets ────────────────────────────────────────────────────────────
DATA_TS="/Users/ellie/Documents/portfolio/src/data/resume.ts"
WEB_KO="/Users/ellie/Documents/portfolio/src/pages/ko/resume.astro"
PDF_KO="/Users/ellie/Documents/portfolio/src/pages/ko/resume-pdf.astro"
OBSIDIAN_MD="/Users/ellie/Desktop/obsidian/hyebin-vault/3-career/resume/resume-common.md"
LINKEDIN_MD="/Users/ellie/Desktop/obsidian/hyebin-vault/3-career/linkedin-about.md"

# Leaf files that must contain actual content strings
declare -a LEAF_FILES=("$DATA_TS" "$OBSIDIAN_MD" "$LINKEDIN_MD")
declare -a LEAF_SHORTS=("data.ts" "common" "LinkedIn")

# Derived files — must just import from data.ts (syntactic check)
declare -a DERIVED_FILES=("$WEB_KO" "$PDF_KO")
declare -a DERIVED_SHORTS=("Web" "PDF")

# ─── Required facts ─────────────────────────────────────────────────────
# REQUIRED_ALL: must appear in all 3 leaf files (data.ts, common, LinkedIn)
declare -a REQUIRED_ALL=(
  "38개 알고리즘|38개"
  "83% 단축|83%"
  "RATB 22~24차|22~24"
  "S&P500 펀드|S&P500"
  "NiceGUI|NiceGUI"
  "3주 → 5일|3주"
  "빌드 741ms|741ms"
)

# REQUIRED_DATA_COMMON: must appear in data.ts + common (LinkedIn is info-only, not required)
# These are facts that are too detailed for LinkedIn About's concise format.
declare -a REQUIRED_DATA_COMMON=(
  "19.5% 수익률|19.5%"
  "다올자산운용 MOU|다올자산운용"
  "mockup-apply|mockup-apply"
)

# ─── Forbidden strings ──────────────────────────────────────────────────
declare -a FORBIDDEN=(
  "22~25차|22~25"
  "RATB 25차|RATB 25"
)

# ─── Header ─────────────────────────────────────────────────────────────
echo ""
echo "🔍 Resume Sync Audit — $(date '+%Y-%m-%d %H:%M')"
echo ""
echo "파일 상태:"
for i in "${!LEAF_FILES[@]}"; do
  if [[ -f "${LEAF_FILES[$i]}" ]]; then
    printf "  ✓ leaf     %-10s %s\n" "${LEAF_SHORTS[$i]}" "${LEAF_FILES[$i]}"
  else
    printf "  ✗ leaf     %-10s MISSING: %s\n" "${LEAF_SHORTS[$i]}" "${LEAF_FILES[$i]}"
  fi
done
for i in "${!DERIVED_FILES[@]}"; do
  if [[ -f "${DERIVED_FILES[$i]}" ]]; then
    printf "  ✓ derived  %-10s %s\n" "${DERIVED_SHORTS[$i]}" "${DERIVED_FILES[$i]}"
  else
    printf "  ✗ derived  %-10s MISSING: %s\n" "${DERIVED_SHORTS[$i]}" "${DERIVED_FILES[$i]}"
  fi
done
echo ""

# ─── Derived files must import from data.ts ────────────────────────────
echo "데이터 소스 연결 검사 (Web/PDF가 data.ts를 import하는가):"
DERIVED_FAIL=0
for i in "${!DERIVED_FILES[@]}"; do
  if grep -q "from.*data/resume" "${DERIVED_FILES[$i]}"; then
    printf "  ✓ %-10s imports from src/data/resume\n" "${DERIVED_SHORTS[$i]}"
  else
    printf "  ✗ %-10s NOT importing from src/data/resume → 하드코딩 드리프트 위험\n" "${DERIVED_SHORTS[$i]}"
    DERIVED_FAIL=$((DERIVED_FAIL + 1))
  fi
done
echo ""

# ─── Check required facts in leaf files ────────────────────────────────
FAIL_COUNT=0

printf "핵심 팩트 존재 검사 (leaf 파일):\n"
printf "  범례: ✓ = 있음, ✗ = 누락, — = 불필요(info-only)\n"
printf "┌─────────────────────────┬──────────┬──────────┬────────────┐\n"
printf "│ %-24s │ %-8s │ %-8s │ %-10s │\n" "키워드" "data.ts" "common" "LinkedIn"
printf "├─────────────────────────┼──────────┼──────────┼────────────┤\n"

# Helper: check a pattern in a file, returns 0/1
check_in_file() {
  local pattern="$1"
  local file="$2"
  if [[ -f "$file" ]] && grep -qF "$pattern" "$file"; then
    return 0
  else
    return 1
  fi
}

# REQUIRED_ALL: all 3 leafs required
for entry in "${REQUIRED_ALL[@]}"; do
  IFS='|' read -r name pattern <<< "$entry"
  cells=()
  for f in "$DATA_TS" "$OBSIDIAN_MD" "$LINKEDIN_MD"; do
    if check_in_file "$pattern" "$f"; then
      cells+=("✓")
    else
      cells+=("✗")
      FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
  done
  printf "│ %-24s │    %s     │    %s     │     %s      │\n" \
    "$name" "${cells[0]}" "${cells[1]}" "${cells[2]}"
done

# REQUIRED_DATA_COMMON: only data.ts + common required, LinkedIn is informational
for entry in "${REQUIRED_DATA_COMMON[@]}"; do
  IFS='|' read -r name pattern <<< "$entry"
  cells=()
  # data.ts + common are required
  for f in "$DATA_TS" "$OBSIDIAN_MD"; do
    if check_in_file "$pattern" "$f"; then
      cells+=("✓")
    else
      cells+=("✗")
      FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
  done
  # LinkedIn is info-only
  if check_in_file "$pattern" "$LINKEDIN_MD"; then
    cells+=("✓")
  else
    cells+=("—")
  fi
  printf "│ %-24s │    %s     │    %s     │     %s      │\n" \
    "$name" "${cells[0]}" "${cells[1]}" "${cells[2]}"
done

printf "└─────────────────────────┴──────────┴──────────┴────────────┘\n"
echo ""

# ─── Check forbidden strings across ALL files ──────────────────────────
FORBIDDEN_HITS=0
declare -a ALL_FILES=("${LEAF_FILES[@]}" "${DERIVED_FILES[@]}")
declare -a ALL_SHORTS=("${LEAF_SHORTS[@]}" "${DERIVED_SHORTS[@]}")

printf "금지 문자열 검사 (모든 파일):\n"
for entry in "${FORBIDDEN[@]}"; do
  IFS='|' read -r name pattern <<< "$entry"
  any_hit=false
  for i in "${!ALL_FILES[@]}"; do
    if [[ -f "${ALL_FILES[$i]}" ]] && grep -qF "$pattern" "${ALL_FILES[$i]}"; then
      printf "  ✗ %-20s → %s\n" "$name" "${ALL_SHORTS[$i]}"
      any_hit=true
      FORBIDDEN_HITS=$((FORBIDDEN_HITS + 1))
    fi
  done
  if ! $any_hit; then
    printf "  ✓ %-20s (없음)\n" "$name"
  fi
done
echo ""

# ─── Summary ────────────────────────────────────────────────────────────
# REQUIRED_ALL × 3 cells + REQUIRED_DATA_COMMON × 2 cells (LinkedIn info-only)
TOTAL_REQUIRED=$(( ${#REQUIRED_ALL[@]} * 3 + ${#REQUIRED_DATA_COMMON[@]} * 2 ))
PASS_REQUIRED=$((TOTAL_REQUIRED - FAIL_COUNT))
echo "결과 요약:"
echo "  데이터 소스 연결: $((${#DERIVED_FILES[@]} - DERIVED_FAIL))/${#DERIVED_FILES[@]}"
echo "  핵심 팩트: $PASS_REQUIRED/$TOTAL_REQUIRED"
echo "  금지 문자열 히트: $FORBIDDEN_HITS"
echo ""

if [[ $FAIL_COUNT -eq 0 && $FORBIDDEN_HITS -eq 0 && $DERIVED_FAIL -eq 0 ]]; then
  echo "🎉 모든 파일이 일관됩니다."
  exit 0
else
  echo "⚠️  드리프트 감지."
  if [[ $FAIL_COUNT -gt 0 ]]; then
    echo "    → 누락 팩트: resume.ts에 해당 내용이 있는지 확인 후 \`npm run sync:resume\`"
  fi
  if [[ $DERIVED_FAIL -gt 0 ]]; then
    echo "    → Web/PDF가 data/resume import를 잃었음. 하드코딩 여부 확인"
  fi
  exit 1
fi
